# Generated by Django 5.2.7 on 2025-11-04 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depth', models.IntegerField(default=0)),
                ('freytag_stage', models.CharField(blank=True, max_length=50)),
                ('story_text', models.TextField()),
                ('critique_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('next_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_choice', to='story.storynode')),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='story.storynode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent_node', 'choice_text'), name='unique_choice_per_node')],
            },
        ),
    ]
