# Generated by Django 5.2.7 on 2025-12-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='클리셰 상세 설명')),
                ('structure_guide', models.JSONField(help_text='스토리 흐름 단계 (발단-전개-절정-결말)')),
                ('example_work_summary', models.TextField(help_text='대표 예시 작품 줄거리 및 감정선')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliches', to='story.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='생성된 스토리', max_length=200)),
                ('user_world_setting', models.TextField()),
                ('twist_point_node_id', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(help_text='전체 시놉시스 (초기)')),
                ('twisted_synopsis', models.TextField(blank=True, help_text='변주 후 변경된 시놉시스')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_cliche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='story.cliche')),
                ('twist_cliche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twisted_stories', to='story.cliche')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('state_data', models.JSONField(default=dict)),
                ('last_updated_node_id', models.IntegerField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_states', to='story.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_phase', models.CharField(max_length=50)),
                ('content', models.TextField(help_text='2000자 내외의 줄거리')),
                ('is_twist_point', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_nodes', to='story.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='story.story')),
            ],
        ),
        migrations.CreateModel(
            name='NodeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('result_text', models.TextField(help_text='선택 직후 행동 묘사')),
                ('is_twist_path', models.BooleanField(default=False)),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='story.storynode')),
                ('next_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='story.storynode')),
            ],
        ),
    ]
