# Generated by Django 5.2.7 on 2025-12-01 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterstate',
            name='last_updated_node_id',
        ),
        migrations.AddField(
            model_name='characterstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterstate',
            name='update_context',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='synopsis',
            field=models.TextField(help_text='초기 전체 시놉시스'),
        ),
    ]
