# Generated by Django 5.2.7 on 2025-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynode',
            name='current_relationships',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storynode',
            name='protagonist_state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
