# Generated by Django 5.2.7 on 2026-01-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_characterstate_last_updated_node_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='twist_cliche',
        ),
        migrations.RemoveField(
            model_name='story',
            name='twist_point_node_id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='twisted_synopsis',
        ),
        migrations.AddField(
            model_name='storynode',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nodechoice',
            name='result_text',
            field=models.TextField(help_text='행동 직후 묘사'),
        ),
        migrations.AlterField(
            model_name='story',
            name='synopsis',
            field=models.TextField(help_text='초기 전체 시놉시스 (Main Plot)'),
        ),
        migrations.CreateModel(
            name='StoryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis', models.TextField(help_text='분기된 시놉시스')),
                ('hierarchy_id', models.CharField(default='', help_text='분기 계층 ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_branches', to='story.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='story.story')),
            ],
        ),
    ]
