# Generated by Django 5.2.7 on 2025-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storynode_current_relationships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynode',
            name='parent_choice_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='storynode',
            name='parent_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
